# SETTINGS
ENV_VAR_PROFILE = "PROJECT_ALIAS_PROFILE"
ENV_VAR_CONFIG_PATH = "PROJECT_ALIAS_CONFIG_PATH"
CONFIG_FILE_NAME = "config"


# MATH
POSITIVE_INFINITY = int(1e9 + 7)
NEGATIVE_INFINITY = -int(1e9 + 7)
ZERO = 0
